### ISSUE TITLE
Specify trace log path via command line

### ISSUE THREAD

**Issue by Zukunftsmusik** [crystalidea/uninstall-tool#10]
Hello,
I was trying to trace several installation packages (custom and therefore detecting **0 installation entries** every time) in sequence using the command line option like: `UninstallTool.exe /install [setup file]` for testing purposes. Unfortunately, after each _install and trace_ I'll have to save the created log (txt) by myself, choosing a name and stuff.

Would be nice, if there was a command line parameter to specify where to save the created installation log file (txt).

I'm using UIT 3.5.4 (Build 5571) x64

**Comment by kleuter** [comment]
Good idea, will be done
