### ISSUE TITLE
Installation log

### ISSUE THREAD

**Issue by zyz696** [crystalidea/uninstall-tool#102]
Hi.
Where do i found the tracked instalaltion log? Like the one showed in the end of installation?
Thanks.

**Comment by zyz696** [comment]
The detailed track window during the instalation,  showed several files, registry keys and process. But on the traced xml file, there's only 4 registry keys and the only file logged was the LNK file created in the user desktop folder.

**Comment by kleuter** [comment]
Currently can be only specified via command line:
https://crystalidea.com/uninstall-tool/command-line
