### ISSUE TITLE
Windows 10/11 dark theme/mode 

### ISSUE THREAD

**Issue by shafi-u** [crystalidea/uninstall-tool#104]
I love this uninstaller tool. The only issue I have is it doesn't follow windows dark theme/mode. 
Is that going to be added any time soon? 
This is the first app I install on any clean installation of windows.

**Comment by kleuter** [comment]
Planned, currently in development

**Comment by kleuter** [comment]
Test build, please give your feedback, thanks
[uninstalltool_setup.zip](https://github.com/crystalidea/uninstall-tool/files/9276819/uninstalltool_setup.zip)

**Comment by shafi-u** [comment]
Runs smoothly. It also works well with darkmode. Did not come across any issues. 👏🏽👏🏽
