### ISSUE TITLE
Bug? Traced data XML view not a bit complete

### ISSUE THREAD

**Issue by Zukunftsmusik** [crystalidea/uninstall-tool#11]
Hello,
when using the option **Traced Data > View as XML...** the displayed XML file seems to be not a bit complete. It shows only one created folder and a bunch of created setup log files in another location. It misses a whole lot of other files and folders created. When I save the UIT log file after tracing (the txt one) it shows that many more files and folders have been created than stated in the XML log.

I'm using
* UIT 3.5.4 (Build 5572) x64
* Windows 7 Enterprise SP 1 (build 7601) x64

**Comment by kleuter** [comment]
Hi,

Which app did you trace?

**Comment by Zukunftsmusik** [comment]
It's a custom application from one of our customers. I can't provide much more information since it's confidential, sorry. I'll see if I can pseudonymize the entries and provide them to you, if it'll help you. But I'm afraid this won't help you without the original installer, right?

**Comment by kleuter** [comment]
Unfortunately, yes, we do need the original installer to check the issue.
