### ISSUE TITLE
Getting error and program closes

### ISSUE THREAD

**Issue by Pcs800** [crystalidea/uninstall-tool#118]
I've been using this for years without issue. Now today I am getting the following, and then the program closes.
I have reinstalled, no change.
![image](https://user-images.githubusercontent.com/80708276/202215885-09b1fb46-373c-4bd8-aa39-58164cef4c28.png)

**Comment by Pcs800** [comment]
If I leave those windows open, i can use the program, however, it thinks I am in trial mode, and re-entering myh registration key does not help.

**Comment by kleuter** [comment]
I wonder where this error message comes from?
![image](https://user-images.githubusercontent.com/2600624/202230510-c9cb47f3-1895-4d6a-bdc1-1358f2d3efb9.png)

Please export the list of installed apps and post it here (zipped).

**Comment by kleuter** [comment]
Latest version of the app? 3.7.1
https://crystalidea.com/downloads/uninstalltool_setup.exe

**Comment by Pcs800** [comment]
Here you go
[Uninstaller.zip](https://github.com/crystalidea/uninstall-tool/files/10024444/Uninstaller.zip)

**Comment by Pcs800** [comment]
When that message window comes up, this file is shown in task manager as running.
![image](https://user-images.githubusercontent.com/80708276/202262810-1fdb111d-fd96-42ea-b06b-6bb3266ff997.png)

**Comment by kleuter** [comment]
Can you please upload this .exe file here? Zipped

**Comment by Pcs800** [comment]
It isn't an exe
[_uninstall16804.zip](https://github.com/crystalidea/uninstall-tool/files/10034581/_uninstall16804.zip)
@kleuter 
The number is different every time I run it.

**Comment by Pcs800** [comment]
Any idea on this? I really don't like not having the uninstaller working.

**Comment by kleuter** [comment]
I'm really sorry for the late reply.

Please try using this build:
https://crystalidea.com/downloads/uninstalltool_setup_beta.exe

And run the app using the /dbg_log command line switch. You can create a shortcut for UninstallTool.exe and specify this switch in the shortcut properties.

![image](https://user-images.githubusercontent.com/2600624/204145216-4bd8c267-0d79-4ded-88b7-8fba74b937af.png)

Run the app using this this shortcut and send the .log file located in the app folder.

**Comment by Pcs800** [comment]
Here you go
[UninstallTool.exe.log.zip](https://github.com/crystalidea/uninstall-tool/files/10106253/UninstallTool.exe.log.zip)

**Comment by kleuter** [comment]
Thanks a lot, now I've got more information.

The helper process "UninstallToolHelper.exe" (required by Uninstall Tool)  is being killed by some other app immediately after startup. Which app? No idea at the moment (you have some many of them installed). I suppose it's the app that throws this error message:

![image](https://user-images.githubusercontent.com/2600624/204382822-a553ddf6-9630-481f-bdeb-6c20832e1e3b.png)

Did you try to run UninstallToolHelper.exe manually? Normally nothing should happen.

May be it would be worth trying to quit apps (one by one) currently running. I recommend using the [SystemInformer tool](https://systeminformer.sourceforge.io/downloads.php) by killing a 3rd party app's processes.

**Comment by kleuter** [comment]
Looks like this _uninstall16804 is coming from the Output arcade app.

**Comment by kleuter** [comment]
Gotcha
![image](https://user-images.githubusercontent.com/2600624/204386043-7e0de2cd-bb8c-456d-81ce-9eb4cf82ca1b.png)

**Comment by kleuter** [comment]
Temporary workaround - install our app to a folder which doesn't contain a space
e.g. not instead of 

```
C:\Program Files\Uninstall Tool
```

use
```
C:\Program Files\UninstallTool
```

**Comment by kleuter** [comment]
The fix is in the official setup:
https://crystalidea.com/downloads/uninstalltool_setup.exe

**Comment by Pcs800** [comment]
That worked!
Awesome, thanks very much.
I do not understand why an audio vst plugin would be killing the uninstaller process, though.

**Comment by kleuter** [comment]
I was wrong about the Arcade app. It was the bug of Uninstall Tool, very rare but it was provoked by the Arcade app.

**Comment by Pcs800** [comment]
Huh, well glad I could help :-)
Thanks for your prompt attention.
