### ISSUE TITLE
Uninstall Tool Menu > Tools > Startup Crash

### ISSUE THREAD

**Issue by Nighted** [crystalidea/uninstall-tool#125]
Hi,

When selecting Startup from the Tools drop down on the Menu then closing the program there is a crash. A blank dialog is popped.

Attached is the dialog and the crash report.

[UnTool_CrashDump.zip](https://github.com/crystalidea/uninstall-tool/files/10521704/UnTool_CrashDump.zip)

**Comment by kleuter** [comment]
Fixed in 3.7.2, thank you
