### ISSUE TITLE
False positive with Norton Internet Security, Latest Update (Uninstall Tool 3.5.5.5580)

### ISSUE THREAD

**Issue by SalisburySorcerer** [crystalidea/uninstall-tool#13]
I noticed tonight that there was a NEW Update dated the 14 April 2018 for Uninstall Tool.

I hurriedly Downloaded this and almost as soon as I had done so, Norton Internet Security Threw a Tantrum and Instantly Removed this Latest Update, saying that there was something Suspicious contained within this Update.

I have retried 3 times, each time the same thing reoccurs??

Any Ideas why Norton would think your Latest Update is Suspicious and then DELETES it?

Your Prompt reply and/or Fix to this problem would really be appreciated.

Thanks

**Comment by kleuter** [comment]
Can you please try the latest build?
https://www.crystalidea.com/downloads/uninstalltool_setup.exe

I've checked it with Norton, it's fine.
