### ISSUE TITLE
Updating the Uninstall Tool

### ISSUE THREAD

**Issue by Spuner** [crystalidea/uninstall-tool#130]
Your site has a new version, but when Uninstall Tool checks for a new version, it says that the latest version is installed. If I understand correctly, checking for a new version is tied to a new version on GitHub. Why do you link checking for updates to a new version on GitHub?

**Comment by kleuter** [comment]
Hi,

Checking for new version is not tied to Github, but this file (currently)
https://crystalidea.com/update/utool.txt

**Comment by Spuner** [comment]
@kleuter, а с официального сайта скачивается 3.7.2.5703.

![2023-07-03 15_37_11-О программе Uninstall Tool](https://github.com/crystalidea/uninstall-tool/assets/30773815/68163bbc-8653-45cd-821e-5d7e890da8fd)

**Comment by Spuner** [comment]
I downloaded this version from the official site...

![2023-07-03 15_37_11-О программе Uninstall Tool](https://github.com/crystalidea/uninstall-tool/assets/30773815/26a890d3-757b-45e3-ab7e-efda390044b1)

And apparently I understood why UT does not see the new version when the official website shows a new version - the problem is that the website does not specify the build, but only the version. Therefore, when only the build is updated, UT does not see the new version.

**Comment by Spuner** [comment]
@kleuter, I downloaded this version from the official site...

![2023-07-03 15_42_54-About Uninstall Tool](https://github.com/crystalidea/uninstall-tool/assets/30773815/a2f10d26-244f-4f21-8ab9-af2c5ce295dd)

And apparently I understood why UT does not see the new version when the official website shows a new version - the problem is that the website does not specify the build, but only the version. Therefore, when only the build is updated, UT does not see the new version.
