### ISSUE TITLE
No windows store app

### ISSUE THREAD

**Issue by RUTHDOMINGUEZ8216** [crystalidea/uninstall-tool#137]
There is no windows store app under "view" tab. How could I get the list of windows app on my computer... I'm using Uninstall Tool 3.7.3

**Comment by kleuter** [comment]
![image](https://github.com/crystalidea/uninstall-tool/assets/2600624/ed3e3845-b4c4-4179-b834-53900ab99e8c)

**Comment by kleuter** [comment]
![image](https://github.com/crystalidea/uninstall-tool/assets/2600624/412189a6-7ec4-4ca8-a331-aedad50cc83b)
