### ISSUE TITLE
Version 3.7.3.5718 installer is recognized as ransomware

### ISSUE THREAD

**Issue by kbr63** [crystalidea/uninstall-tool#138]
While dowloading installer for update 3.7.3.5718 from your net page, F-Secure virus protection software takes uninstaltool_setup.exe file directly in quarantine and gives alarm about ransomware.
https://www.f-secure.com/v-descs/ransomware.shtml
This has never happened before. Whats going on?

**Comment by kleuter** [comment]
This is a false positive, we reverted the installer to build 5717 and will investigate the issue further.

Thanks for the report.

**Comment by kleuter** [comment]
Issue reproduced, will contact f-secure now

**Comment by kleuter** [comment]
5719 is clean now

**Comment by kbr63** [comment]
Thank you for the quick service and for taking the matter seriously.
