### ISSUE TITLE
Icon Disappering

### ISSUE THREAD

**Issue by Jeremy-yjl** [crystalidea/uninstall-tool#149]
Uninstall Tool can not get icons of Windows Store Apps which appear blank default icons on it.
Furthermore, after switching back to Application Page from Windows Store Apps Page, icons of Applications go blank too.
![屏幕截图 2024-04-18 104439](https://github.com/crystalidea/uninstall-tool/assets/136414552/cd4f50b4-7cce-49e5-822a-d151a19ced44)
![image](https://github.com/crystalidea/uninstall-tool/assets/136414552/20d32dab-62fb-42d4-8f69-d64e427a3029)

**Comment by kleuter** [comment]
It's probably because you don't have a valid license for the app 😉
