### ISSUE TITLE
Context Menu: Repeated ShellExtension.

### ISSUE THREAD

**Issue by hovan-kau** [crystalidea/uninstall-tool#151]
<ShellExtension>
        **<InstallWithInstallTracker>Install and trace with Install Tracker...</InstallWithInstallTracker>**
        <InstallWithInstallTrackerTip>Install and trace all the changes a program makes on your computer</InstallWithInstallTrackerTip>
        **<InstallWithInstallTrackerShort>Install with Install Tracker</InstallWithInstallTrackerShort>**
        <uninstallWithUninstallTool>Uninstall with Uninstall Tool</uninstallWithUninstallTool>
        <uninstallWithUninstallToolFailed>Unable to detect any application based on the provided shortcut:</uninstallWithUninstallToolFailed>
        <uninstallWithUninstallToolConfirm>Are you sure you want to completely remove '%s' and all of its components?</uninstallWithUninstallToolConfirm>
    </ShellExtension>

This problem appears in all language versions.
Only for msi and exe.

<img width="237" alt="image" src="https://github.com/crystalidea/uninstall-tool/assets/50275551/df6050a5-25ec-48fd-922b-d865faa52f7e">

**Comment by kleuter** [comment]
- Does it happen in Windows Explorer? 
- Any Explorer tweaks installed?
- Windows 11 version?

**Comment by hovan-kau** [comment]
1.Only by right-clicking on MSI and EXE files, no matter where they are, this will happen. (Windows 11 context menu)
2.No any Explorer tweaks have been installed.
3.windows 11 22637.3737

My problem has been solved. The reason for the generation of repeated items in the context menu is the installation of "UTShellExt2", which specifically adds a project to the new-style contextmenu of Windows 11, but does not delete the old Shellext.

Using the uninstall tool to delete UTSHELLEXT2 in MS APPs can solve the problem.
