### ISSUE TITLE
Verdict: LIKELY_MALICIOUS What?

### ISSUE THREAD

**Issue by Katrine2233** [crystalidea/uninstall-tool#158]
I have been using your program for many years and suddenly a well-known antivirus software (dr. web) removes it. And Virustotal recognizes it as a Trojan. If it were some little-known antivirus, I would ignore it, but Dr. Web is not like that.
https://www.virustotal.com/gui/file/8c893f0e38cfb93272f59f03a4beed05182bcb48ab3454531bfc24dde2110294/detection
![2024-09-07_10-56-14](https://github.com/user-attachments/assets/841903e4-7ad6-4b7f-845a-960a2d8ef6e5)

**Comment by kleuter** [comment]
The link gives 0 out 74 now.
