### ISSUE TITLE
Portable Bug?

### ISSUE THREAD

**Issue by dtoxic47** [crystalidea/uninstall-tool#160]
So the portable version although i stores preferences in program folder the CachedData.dat and Traced programs are still being stored in
"C:\Users\XXXX\AppData\Roaming\CrystalIdea Software\Uninstall Tool

Could we get a "true" portability? where all the data is stored in the Program folder. or is this a bug?

**Comment by kleuter** [comment]
It's not a bug, but cache is indidual to every computer, that's the 'issue'
