### ISSUE TITLE
Uninstall does not complete the process

### ISSUE THREAD

**Issue by Ben-Johnson1940** [crystalidea/uninstall-tool#20]
I have used Geek 145126 to remove an Antivirus software called "Avista" (Czech software, which I found installed on my computer) and used the force removal option. The process finds the files and reports completion. In the Windows (8.1) Programs and features, the entries for Avista are no longer there. The programs however ares sill there and there are four entries in the Task Manager for this software. My problem is that I have another virus protection system in use and I need to update it, but the update reports that an incompatible system needs to be removed first. This where I am stuck.
I ran the trial software without success, because it does not find the software.

**Comment by kleuter** [comment]
If the app is not listed in the apps, there's nothing we can do. Try removing it manually.
