### ISSUE TITLE
Is this a product you intend to purchase to leave garbage in your PC?

### ISSUE THREAD

**Issue by nbm06098** [crystalidea/uninstall-tool#21]
If you perform uninstallation before entering the key, it will be impossible to get back to work halfway.
There seems to be some garbage left, but there is no way to find out what is left.
It is guided by software purchase, but it can not be repaired where I purchased it.
This is terrible.

**Comment by kleuter** [comment]
When the app is not yet registered, a user is able to save leftovers after uninstallation:
![sshot-2018-06-20- 14-49-56](https://user-images.githubusercontent.com/2600624/41659334-467c3da8-7499-11e8-8cbb-b8d46184ae2f.png)
