### ISSUE TITLE
Where is the file which contains the result of an install (i.e. all files and registry settings)?

### ISSUE THREAD

**Issue by Steve-McCandlish** [crystalidea/uninstall-tool#25]

**Comment by kleuter** [comment]
C:\Users\%USER%\AppData\Roaming\CrystalIdea Software\Uninstall Tool\Traced

**Comment by Steve-McCandlish** [comment]
There is no "traced" file or folder. I did install use the Install and Trace feature.

**Comment by kleuter** [comment]
If an app appears in with a traced symbol (an 'eye') in the list of apps, then its traced data is stored there.
You can also use context menu Traced Data to view the xml data.
https://www.crystalidea.com/assets/images/uninstall-tool/screen_monitor_append.png
