### ISSUE TITLE
Missing icons for some Windows Store apps

### ISSUE THREAD

**Issue by kleuter** [crystalidea/uninstall-tool#29]
Groove Music
Get Help
People
Maps 
and some others.

**Comment by i5151** [comment]
Windows Store Apps:
Movies & TV

Apps：
LAV Filters
ICBCChromeExtension
Microsoft Visual C++ series
Intel（R）C++ Redistributable on Intel（R）series

System：
Office Click-to-Run series
Microsoft Visual C++ series
intel（R）series
Connection Manager

Hidden：
WIC
InstallShield Uninstall Information
Alipay series

**Comment by i5151** [comment]
Version 3.5.8 opens the Windows Store app very slowly, and in the best case, not all apps can display icons. More often, after waiting for a long time, almost all apps don't display icons.

**Comment by kleuter** [comment]
@i5151 
is Windows on SSD drive? Please post a screenshot here. Thank you

**Comment by i5151** [comment]
Yes, on SSD drive.
![Snipaste_2019-05-29_22-00-32.png](https://z4a.net/images/2019/05/29/Snipaste_2019-05-29_22-00-32.png)
![Snipaste_2019-05-29_22-01-55.png](https://z4a.net/images/2019/05/29/Snipaste_2019-05-29_22-01-55.png)

**Comment by kleuter** [comment]
Got it, it's a special "feature" against people who don't like buying software :)
Please download the official [3.5.8 build][x]

[x]: https://www.crystalidea.com/downloads/uninstalltool_setup.exe

**Comment by i5151** [comment]
I bought the genuine version, and downloaded the latest version on the official website. When I contacted the customer service by email, I sent the serial number to the customer service for verification.

**Comment by kleuter** [comment]
Please contact us at support@crystalidea.com specifying your license key. Thanks.

**Comment by i5151** [comment]
I sent emails to Steven Meyer very early, and he verified it. He asked me to give you more details here.

**Comment by kleuter** [comment]
Ok, please post screenshot of your About dialog

**Comment by kleuter** [comment]
Ok, please post screenshot of your About dialog, example:
![sshot-2019-05-29- 16-43-31](https://user-images.githubusercontent.com/2600624/58566419-edbae380-8230-11e9-92ba-f68fa9d85f76.png)

**Comment by i5151** [comment]
I have sent it by mail, and there is personal information here.
![Snipaste_2019-05-29_22-45-29.png](https://z4a.net/images/2019/05/29/Snipaste_2019-05-29_22-45-29.png)
I will delete it after you verify it.

**Comment by kleuter** [comment]
Yes, could you please try this [build](https://www.crystalidea.com/downloads/UninstallTool_5621.zip)?

**Comment by i5151** [comment]
Running error.
![Snipaste_2019-05-29_23-37-50.png](https://z4a.net/images/2019/05/29/Snipaste_2019-05-29_23-37-50.png)

**Comment by kleuter** [comment]
Please put the .exe inside the app folder.

**Comment by i5151** [comment]
I see, but it's exactly the same as build 5620.

**Comment by i5151** [comment]
OS is Windows 10 18362.116.

**Comment by kleuter** [comment]
Updating to Windows 10 1903...

**Comment by kleuter** [comment]
Well, it works fine here:
![sshot-2019-05-30- 11-11-07](https://user-images.githubusercontent.com/2600624/58622401-cbc26f00-82cb-11e9-83c7-0cc1d1c2262c.png)

Can you please record a video? Starting the app -> Windows Store Apps

**Comment by i5151** [comment]
https://c-t.work/s/76542a188af646
In order to know the waiting time, the previous picture is not deleted; in order to reduce the file size, the video quality is lowered.

**Comment by kleuter** [comment]
please try this [build](https://www.crystalidea.com/downloads/UninstallTool_5622.zip) and send us the UninstallTool.exe.log file after Windows Store Apps are loaded. Thank you

**Comment by i5151** [comment]
https://c-t.work/s/af4d3df2efd645

**Comment by kleuter** [comment]
thank you, please tell me your screen resolution!

**Comment by i5151** [comment]
3840X2160 250% 15.6"

**Comment by kleuter** [comment]
Thank you! Reproduced, will fix the icons soon, please stay tuned.

**Comment by kleuter** [comment]
1. Icons must be fixed now, please try this build, do not forget to Refresh (F5) the list of apps.
2. Slow loading can't be fixed, for some reason the IPackage::get_InstalledLocation() system call takes around 0.3 seconds for each app, which quite a lot. No idea why it happens

**Comment by i5151** [comment]
Thanks, exactly the same as the previous version.

**Comment by kleuter** [comment]
Press the F5 key

**Comment by i5151** [comment]
After pressing the F5 key, icons are displayed except for the five APPs, and two icons are just color blocks. I have waited for a long time again. This is not a normal software state, I am waiting for you to completely improve it.

**Comment by kleuter** [comment]
Slow loading can't be fixed, for some reason the IPackage::get_InstalledLocation() system call takes around 0.3 seconds for each app, which quite a lot. No idea why it happens, please try reinstall Windows

**Comment by i5151** [comment]
3.5.7 loads very fast.

**Comment by kleuter** [comment]
Can you make a video with 3.5.7 please?
