### ISSUE TITLE
Ver.4

### ISSUE THREAD

**Issue by g335c** [crystalidea/uninstall-tool#33]
Do I have to pay a major update after several months of purchase?

-I used a translation service-

**Comment by g335c** [comment]
[kleuter]

A you alive?
January 15, 2019 Last reply

**Comment by kleuter** [comment]
https://www.crystalidea.com/uninstall-tool/buy
![sshot-2019-02-17- 11-44-08](https://user-images.githubusercontent.com/2600624/52911817-682aad80-32a9-11e9-8030-7d5ff67c9f13.png)
