### ISSUE TITLE
Skype not visible 

### ISSUE THREAD

**Issue by RemovingFreak** [crystalidea/uninstall-tool#34]
Skype is not visible although accessible via Windows uninstall.

**Comment by kleuter** [comment]
Could you please show some screenshots?

**Comment by RemovingFreak** [comment]
Hello, Sure. See the following :

[image: image.png]
:


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kleuter** [comment]
Unfortunately, I don't see any picture
