### ISSUE TITLE
No button is pressed with the name of the program in the list of updated programs in the lower right corner of the screen

### ISSUE THREAD

**Issue by rushelex** [crystalidea/uninstall-tool#35]
No button is pressed with the name of the program in the list of updated programs in the lower right corner of the screen

**Comment by kleuter** [comment]
Do you mean that link with the name of a recent app is not-clickable? What's your screen resolution?

**Comment by rushelex** [comment]
Yes. Resolution 1920x1080.

**Comment by kleuter** [comment]
Can you please record a video?

**Comment by rushelex** [comment]
Yes. Link: https://drive.google.com/open?id=1wN5-cHbo0pcn2vivmGKjT7qINIO_HUMJ

**Comment by kleuter** [comment]
Ok, thank you. Please post a screenshot of the About dialog here.

**Comment by rushelex** [comment]
Yes. Link on screenshots: https://drive.google.com/file/d/1XfwT84s6eBA4ht3lvYKSzZOcZw1EnTe3/view?usp=drivesdk
https://drive.google.com/file/d/1-0-VpcwPd0L_pUY2D5SD8qp3ofDcXbca/view?usp=drivesdk

**Comment by kleuter** [comment]
No, I got me wrong. This screenshot
![sshot-2019-06-05- 13-24-14](https://user-images.githubusercontent.com/2600624/58952909-46403280-8795-11e9-934d-afc0969ff1d4.png)

**Comment by kleuter** [comment]
that's what I thought 😉

**Comment by rushelex** [comment]
I work in a big company. More data can not tell, because it is confidential.
![sshot-6](https://user-images.githubusercontent.com/41122157/59144369-71728e00-89f0-11e9-835d-aa65f4f4efe1.png)
