### ISSUE TITLE
No button is pressed with the name of the program in the list of updated programs in the lower right corner of the screen

### ISSUE THREAD

**Issue by rushelex** [crystalidea/uninstall-tool#37]
No button is pressed with the name of the program in the list of updated programs in the lower right corner of the screen.

Resolution 1920x1080.

Video: https://drive.google.com/open?id=1wN5-cHbo0pcn2vivmGKjT7qINIO_HUMJ

About:
![sshot-6](https://user-images.githubusercontent.com/41122157/59144401-d0380780-89f0-11e9-8ccf-87345f0be4e7.png)

**Comment by kleuter** [comment]
It's a patched version of Uninstall Tool, pirated copy. And this is the only reason why you cannot click on a program name in the popup window.
