### ISSUE TITLE
Start traking programm installation without admin rights.

### ISSUE THREAD

**Issue by PeRFecTxTabZ** [crystalidea/uninstall-tool#38]
I cant install spotify with tracking of the uninstall programm because the spotify installer can only be startet without admin rights.

**Comment by kleuter** [comment]
Confirmed
![sshot-2019-09-06- 09-37-33](https://user-images.githubusercontent.com/2600624/64409852-fe79c180-d089-11e9-9f7c-08acf7ef404c.png)

**Comment by kleuter** [comment]
Fixed in 3.5.9 build 5653
