### ISSUE TITLE
Install & trace program error

### ISSUE THREAD

**Issue by budgall** [crystalidea/uninstall-tool#42]
Received this screen when trying to trace the install of a program. How do I fix?

![UninstallToolError](https://user-images.githubusercontent.com/54972691/64402161-b5ddec00-d028-11e9-9692-7a1345df948d.png)

**Comment by kleuter** [comment]
- What is the name of the setup file you're trying to install? 
- Are you using Install Tracker from the app or via context menu of the setup file?
- Which version of Uninstall Tool are you running?

**Comment by kleuter** [comment]
Fixed, please re-download the app
https://www.crystalidea.com/downloads/uninstalltool_setup.exe
