### ISSUE TITLE
No icons for Windows Store apps in 3.5.9

### ISSUE THREAD

**Issue by i5151** [crystalidea/uninstall-tool#43]
Click the Windows Store tab and it opens very slowly. And the result of opening is this:
![Snipaste_2019-09-06_14-45-06.png](https://z4a.net/images/2019/09/06/Snipaste_2019-09-06_14-45-06.png)

3.5.9 build 5652

**Comment by kleuter** [comment]
Slow loading can't be fixed, for some reason the IPackage::get_InstalledLocation() system call takes around 0.3 seconds for each app (on your machine!), which is quite a lot. No idea why it happens, please try reinstall Windows

**Comment by i5151** [comment]
I understand, but the icons of these apps are not displayed.

**Comment by kleuter** [comment]
Try to clear cache by pressing the F5

**Comment by i5151** [comment]
The result is the same.

**Comment by kleuter** [comment]
Working on a fix... thank you

**Comment by kleuter** [comment]
Fixed in the build 5654

**Comment by i5151** [comment]
Yes, you did it. thank you very much.

Just the first time there are no icons, I have to refresh once and the icons are displayed.

**Comment by i5151** [comment]
Sorry, I tried a few times and the icons can be displayed after the first opening. This build is OK. thank you very much!

**Comment by kleuter** [comment]
Thank you for the report!

**Comment by i5151** [comment]
I just noticed a detail, the Windows APP icons are all upside down.

![Snipaste_2019-09-09_20-32-20.png](https://z4a.net/images/2019/09/09/Snipaste_2019-09-09_20-32-20.png)

**Comment by kleuter** [comment]
Thanks, please check the last build (press F5)

**Comment by i5151** [comment]
No change.

**Comment by kleuter** [comment]
Please press the F5, Refresh

**Comment by i5151** [comment]
Only the first time I need to refresh, I don't need it later. Great, thanks!
