### ISSUE TITLE
Problem in Uninstall latest version 3.5.9 Build 5650 x64

### ISSUE THREAD

**Issue by Ariele47** [crystalidea/uninstall-tool#44]
![image](https://user-images.githubusercontent.com/28765975/64416265-26bbed00-d097-11e9-80ad-fb2d6ad0a4d6.png)

**Comment by kleuter** [comment]
Thank you and sorry for the bug introduced, it's fixed the the latest [build](https://www.crystalidea.com/downloads/uninstalltool_setup.exe)
