### ISSUE TITLE
some trouble

### ISSUE THREAD

**Issue by TiltName7** [crystalidea/uninstall-tool#46]
uninstall tool can't find two programs that now need to be deleted. In their folders there aren't uninstall file. How to delete this programs?

**Comment by kleuter** [comment]
Which programs?

**Comment by TiltName7** [comment]
Risk of Rain 2, downloaded from Internet (not Steam)

**Comment by kleuter** [comment]
If this apps do not appear in the list of apps, there's no way of deleting them except of reinstalling again and then uninstall (once they appear in the list)
