### ISSUE TITLE
Right click no install win10

### ISSUE THREAD

**Issue by peter01973** [crystalidea/uninstall-tool#47]
Hi,
Im using win10 home + uninstall tool 3.5.9 and i have been able to right click on a program when installing it for the first time and then choose install and track with uninstall tool but i cant do that anymore, nothing is being installed unless i install the program without right click, using tace with uninstall toll

**Comment by andersenpeter24** [comment]
No one else having this issue in windows 10

**Comment by kleuter** [comment]
Did you try to reinstall the app?

**Comment by andersenpeter24** [comment]
yes i uninstalled it today installed the 3.5.9 x64 version but still same issue

**Comment by andersenpeter24** [comment]
im using windows 10 ver 1909

**Comment by kleuter** [comment]
Do you see the context menu after performing the right click?
![image](https://user-images.githubusercontent.com/2600624/79437113-0ad7dc80-7fd2-11ea-87c4-e0afb1461f36.png)

**Comment by andersenpeter24** [comment]
Yes i can see this when i right click but then nothing happens after i click install and trace with...

**Comment by andersenpeter24** [comment]
im running this as admin

**Comment by kleuter** [comment]
Please try to select this setup in Uninstall Tool:
![image](https://user-images.githubusercontent.com/2600624/79438984-8fc3f580-7fd4-11ea-86f2-16acf73cbc38.png)
Does it work?

**Comment by andersenpeter24** [comment]
Yes that is working from inside the uninstall tool as you show on the above attached photo

**Comment by kleuter** [comment]
Please try to extract this [file](https://crystalidea.com/downloads/tools/utshellext_update.zip) into the program folder, then run utshellext_update.bat as administrator. After that please try "Install and Trace with..."

**Comment by andersenpeter24** [comment]
I tried to run the above file but now when i right click on a file to install i get an info saying cannot start uninstall tool error 740, perhaps its because i have my uninstall tool install on another harddrive, not C drive or ?

**Comment by kleuter** [comment]
Error 740 means that the operation requires elevation. Please let me create one more version to test

**Comment by kleuter** [comment]
Please extract this [file](https://crystalidea.com/downloads/tools/utshellext_update2.zip) into the program folder then run `utshellext_update.bat` as administrator
 After that please try "Install and Trace with..." again. Thanks.

**Comment by andersenpeter24** [comment]
![image](https://user-images.githubusercontent.com/30890685/79444248-3d3a0780-7fdb-11ea-858f-cc0be18ae44d.png)
i still get this message, sorry to give you all this problem

**Comment by andersenpeter24** [comment]
But i can still run the program with this UninstallTool.exe but the right click feature gives the above error

**Comment by kleuter** [comment]
It's the old utshellext.dll, please make sure have the new one (from utshellext_update2.zip)

**Comment by andersenpeter24** [comment]
Perfect now its working with the  utshellext_update2.zip into GREAT / how should i do now because i need to format my windows 10 PC and reinstall everything again, when i install uninstall tool again, do i have to use the  utshellext_update2.zip again + in the future to avoid this ? but thank you very very much for all your help / time on this issue

**Comment by kleuter** [comment]
We'll put this fix into the main download soon

**Comment by andersenpeter24** [comment]
Great news - thank you, have a nice day

**Comment by kleuter** [comment]
Fixed in 3.5.10
https://github.com/crystalidea/uninstall-tool/releases/download/v3.5.10/uninstalltool_setup.exe

**Comment by andersenpeter24** [comment]
You r the best  !!
thanks :)

**Comment by kleuter** [comment]
Thank you for reporting the issue!
