### ISSUE TITLE
проблема с активацией

### ISSUE THREAD

**Issue by biser1954** [crystalidea/uninstall-tool#58]
При покупке Uninstall tool указал неправильный адрес электронной почты теперь не могу получить код и пароль для активации

**Comment by kleuter** [comment]
Which email is correct/incorrect ?

**Comment by biser1954** [comment]
код активации нужно отправить на terem974@mail.ru30.01.2021, 14:33, "Kleuter" <notifications@github.com>:
Which email is correct/incorrect ?

**Comment by kleuter** [comment]
Sent.
