### ISSUE TITLE
Removing residiaul stuff left after an app uninstall

### ISSUE THREAD

**Issue by emma313823** [crystalidea/uninstall-tool#59]
Hi
I thought I would try a different app besides Revo, so I bought the Geek Uninstaller Pro, however I'm  having some issues figuring out how to do this.

I have several apps I uninstalled using the normal Windows 10 Control Panel for uninstall, however when I go to my program folders I see stuff was left over. In Revo I would do the force uninstall and it would find all that leftover stuff - regedit etc and I could clean it all up. I don't understand how I can achieve this. Can anyone offer some guidance on how to do this?

Emma

**Comment by kleuter** [comment]
Hi,

Removing leftovers is only possible when uninstalling via Uninstall Tool not via the Windows 10 Control Panel.
