### ISSUE TITLE
Installed programs

### ISSUE THREAD

**Issue by Spuner** [crystalidea/uninstall-tool#63]
After starting the system, in the Uninstall Tool, some software is shown as newly installed, but they were installed a long time ago. And so every time, the date of installation of these software changes with each launch of the system. There is no such bug on Windows 7. This bug has always been on Windows 10, even on 21H1.

OS: Windows 10 Pro 21H1 (Build 19043.1081)
Uninstall Tool 3.5.10 (Build 5670)

**Comment by kleuter** [comment]
Thanks for the report.

Could you please provide some screenshots please?

**Comment by Spuner** [comment]
Recorded a video. For example, SpeedFan was installed on September 17, 2020, but Uninstall Tool shows it was installed on August 1, 2021. It's like this every time. It happens not only with SpeedFan, but also with some other programs (Steam, MSI Afterburner, etc.).

https://user-images.githubusercontent.com/30773815/127775579-26c4af1b-26e7-4679-9a90-c2f9745baf80.mp4

**Comment by Spuner** [comment]
Sorry, but the above bug will be fixed or not?

**Comment by kleuter** [comment]
Dedection of installation date is improved in the last update (3.6).

If you still have a complaint, please report a new issue with specifying a certain app, its download link to reproduce.
