### ISSUE TITLE
Is the Uninstaller Tool still being developed?!

### ISSUE THREAD

**Issue by HRSAN** [crystalidea/uninstall-tool#64]
I have a feeling the dev of this app is not focusing anymore in giving regular updates. I have paid to buy a lifetime license but little did i know the app wasnt being updated to match new programs coming out, new software detections, left overs etc.. HibitUninstaller competes with this tool even can become better at sometimes.

**Comment by kleuter** [comment]
Absolutely, major update is planned as well.
