### ISSUE TITLE
Uninstall lost program files menu

### ISSUE THREAD

**Issue by Rickeyjt** [crystalidea/uninstall-tool#65]
I fully uninstalled about six programs and noticed my Programs menu in win10 pro is now missing about 2/3 of my program list. If uninstall is doing some heavy cleaning then it looks like maybe it does not understand removing everything related to one program may have parts that other kept programs are co-dependent on?

Also some programs required re-installation because of this.

**Comment by kleuter** [comment]
No further data provided unfortunately.

This issue has been closed since there has not been any recent activity. Please re-open it if needed.
