### ISSUE TITLE
Uninstall Tool

### ISSUE THREAD

**Issue by uffbros** [crystalidea/uninstall-tool#7]
The install and trace feature doesn't work in the portable version. Are you aware of this? 
![capture 2](https://user-images.githubusercontent.com/36732579/36538351-0f6d89b6-17a1-11e8-8e88-87a40864a53a.JPG)

**Comment by kleuter** [comment]
In order to activate the portable license, one has to use **license.dat** file
https://www.crystalidea.com/uninstall-tool/activate-after-purchase
