### ISSUE TITLE
Problem & Feature: Cannot reach the "uninstall" click in a long window

### ISSUE THREAD

**Issue by zenglinxing** [crystalidea/uninstall-tool#73]
When I was about to uninstall a program, I found that it had a lot of attached programs(maybe because I was installing another program when I installed this program). In the case you could see in the picture, it popped out a window displaying those attached programs in a long window. However, my screen's height is so limited (1080p) that I could not reach the end of the window. Therefore, I could not uninstall the program at the moment.
According to the circumstances, I suggest the developers of Uninstall Tool to add a scroll bar in this window, so that when plentiful of attached programs popped out, it could narrow the height of pop window.
![long_window_problem-submitted](https://user-images.githubusercontent.com/54155246/143380688-a160551a-424e-4a4b-b65a-968d199c2857.png)

**Comment by kleuter** [comment]
Fixed in 3.7.4
