### ISSUE TITLE
Install finished, but uninstall tool keeps monitoring

### ISSUE THREAD

**Issue by orthemius** [crystalidea/uninstall-tool#76]
Hi. 
Sometimes installation of app is finished but uninstall tool keeps monitoring and it's impossible to understand what is it waiting for.
How can I see the processes that are still runing?

**Comment by kleuter** [comment]
It's not currently possible to the list of processes but it's definetely one of the processes that was created during the installation. It's recommended to quit the Install monitor and stop waiting manually in such situations.
