### ISSUE TITLE
winget support?

### ISSUE THREAD

**Issue by Macleykun** [crystalidea/uninstall-tool#81]
Saw it was also on choco and though, why not also make it for winget possible :) ?

**Comment by Macleykun** [comment]
I'm also making winget support here: https://github.com/microsoft/winget-pkgs/pull/46503
so i can help out with this aswell! however, does uninstall-tool have a silent parameter/argument? With 0 user interraction?

**Comment by Macleykun** [comment]
Sorry my bad, idk how i missed this:
https://github.com/microsoft/winget-pkgs/commit/b1a7bb56c7438105fad574cc6b022d772362eafd
I'll close this xD i'm personally not so into choco, but it's up to you if ya want to.

fijn weekend!

**Comment by Macleykun** [comment]
Hi hi, about the winget support.
I wanted to ask two things:
1. Is it possible to keep each version in a separate static url perhaps? Now everytime a change happens, the winget will fail to install.
2. Does the sha265 change every x weeks/days? I've updated it: https://github.com/microsoft/winget-pkgs/pull/95090/files but also did this before: https://github.com/microsoft/winget-pkgs/pull/93528/files . I assume the file doesn't change in hash right?

**Comment by kleuter** [comment]
Hi, the issue is that sometimes we do not increment the version but only the build number (when an urgent fix is required).

Probably it's not the best method, but that's how it works for years...

**Comment by Macleykun** [comment]
> Hi, the issue is that sometimes we do not increment the version but only the build number (when an urgent fix is required).
> 
> Probably it's not the best method, but that's how it works for years...

Is it possible to have an url that's fixed to a version? like domain.xyz/release/program.1.2.3?
And to maybe suggest to change the version if the file changes perhaps?

**Comment by Macleykun** [comment]
hey @kleuter , i noticed that the hash has changed again.
Is it possible to maybe host a direct link to a specific version maybe?

**Comment by Macleykun** [comment]
hey @kleuter is the above an idea?
