### ISSUE TITLE
Cylance Protect Not Uninstalled But Doesn't Show Up In Uninstall Tool 3.5.10 After Forced Removal

### ISSUE THREAD

**Issue by sidconnor** [crystalidea/uninstall-tool#85]
Hi - 

I used Unistall Tool 3.5.10 to remove Cylance Protect from my Windows 10 PC and had to use the Force Removal option but, Cylance Protect still shows up in my startup menu and as a process in Task Manager after rebooting. What do I need to do to actually remove it from my system?

Thanks

**Comment by kleuter** [comment]
https://cyberforcesecurityhelp.freshdesk.com/support/solutions/articles/44002036687-manual-removal-of-cylanceprotect
