### ISSUE TITLE
Remove Windows XP/Vista from supported OS list on website

### ISSUE THREAD

**Issue by whitebear60** [crystalidea/uninstall-tool#88]
[Here](https://crystalidea.com/uninstall-tool/support) (idk, possibly in other places too) Windows XP and Vista still listed as supported OS, however, Release Notes state, that they are unsupported, as of 3.6.0

**Comment by kleuter** [comment]
Hi, Mihail.

Actually, XP and Vista are supported in the legacy, separate download.
I will improve the text anyways, thank you.

Слава Україні.
