### ISSUE TITLE
Bug after updating version 3.60！

### ISSUE THREAD

**Issue by cobition** [crystalidea/uninstall-tool#89]
After updating the version 3.60, I can't launch Insrall Tracker from the right-click menu for a setup file !

**Comment by kleuter** [comment]
do you have NVIDIA gpu?

**Comment by cobition** [comment]
Yes, RTX 3060



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月15日 18:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [crystalidea/uninstall-tool] Bug after updating version 3.60！ (Issue #89) |

do you have NVIDIA gpu?

**Comment by kleuter** [comment]
Working on a fix right away

**Comment by cobition** [comment]
Thanks!



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月15日 18:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [crystalidea/uninstall-tool] Bug after updating version 3.60！ (Issue #89) |

Working on a fix right away

**Comment by kleuter** [comment]
https://crystalidea.com/downloads/uninstalltool_setup_test.exe

Please try this build.

**Comment by cobition** [comment]
Great！the bug has been fixed in this build, thanks!

**Comment by kleuter** [comment]
Fixed in the last update
