### ISSUE TITLE
Windows 11: invalid installation date for apps (Dec 31, 1970)

### ISSUE THREAD

**Issue by kleuter** [crystalidea/uninstall-tool#93]
Some people report 
`Under Uninstaller all programs under the Windows Installed Apps Tab show an Installed On Date of Dec 31, 1970.`

Does it happen for anyone too?

**Comment by EricLyon17a** [comment]
I hope that the following screen shots may help regarding this issue

![image](https://user-images.githubusercontent.com/106491840/170889395-84856608-75b6-4c60-bf5c-a8c1e7200343.png)

![image](https://user-images.githubusercontent.com/106491840/170889461-a15e4132-7093-4644-bbae-4f1c27bfef74.png)

![image](https://user-images.githubusercontent.com/106491840/170889489-74644670-5665-4361-a01f-9ffb9cb04f5e.png)

**Comment by EricLyon17a** [comment]
My windows11 version

![image](https://user-images.githubusercontent.com/106491840/170889812-b5b70fdc-c2b3-4cd9-b088-8a244098def4.png)

**Comment by kleuter** [comment]
thanks guys, will be fixed soon.

**Comment by EricLyon17a** [comment]
![image](https://user-images.githubusercontent.com/106491840/170971986-797d837b-1d63-4c68-8923-4139dca8abab.png)
