### ISSUE TITLE
Uninstall tool 会导致右键单击快捷方式`以管理员身份运行`无响应

### ISSUE THREAD

**Issue by RainYQ** [crystalidea/uninstall-tool#94]
似乎`utshellext.dll`被资源管理器加载之后就会导致右键的`以管理员身份运行`无响应，重启后删除该文件就会恢复
windows version: Windows 11 专业版 - 21H2 - 22000.708; Windows 功能体验包 1000.22000.708.0
uninstall tool version: 3.6.0

**Comment by kleuter** [comment]
Please provide some screenshots of video and reopen the issue.

**Comment by RainYQ** [comment]
Sorry, the video file size is bigger than 10MB.
链接：https://pan.baidu.com/s/1pa6dXLnywFGjHheZy2h3Hg?pwd=omma 
提取码：omma

**Comment by kleuter** [comment]
https://windowsreport.com/windows-11-right-click-show-all-options/#:~:text=To%20access%20the%20old%20right,F10%20after%20selecting%20an%20item.
