### ISSUE TITLE
Install Tracker causes BSOD in Windows 11 22H2

### ISSUE THREAD

**Issue by TigerBeanst** [crystalidea/uninstall-tool#97]
![image](https://user-images.githubusercontent.com/3889846/172741310-c7a56a51-1b4e-4b90-a4d5-a97fc7d97c70.png)

![image](https://user-images.githubusercontent.com/3889846/172740861-99e07f68-eabd-495b-8893-5819fc6842ba.png)

Or right-click in Explorer to track an installation act as the same.

![e100edbe98f4f2e2aeb983cd3edd798](https://user-images.githubusercontent.com/3889846/172741031-c33c1cb3-e797-4290-8429-1a2db67e3a8b.jpg)

![image](https://user-images.githubusercontent.com/3889846/172741189-39429f06-6530-452c-ab88-8c9c6298efd4.png)

There is some Chinese in the screenshots, but it shouldn't cause any dyslexia

**Comment by kleuter** [comment]
Reproduced the problem, indeed happens in 21H2

**Comment by kleuter** [comment]
Please try the new build:
https://crystalidea.com/downloads/uninstalltool_setup_nobsod.exe

**Comment by MarDrs** [comment]
> Please try the new build: https://crystalidea.com/downloads/uninstalltool_setup_nobsod.exe

I just checked the new 5685 build of the program.

Thanks, it works without errors!

Best regards,
MD

**Comment by kleuter** [comment]
Thanks for the follow up!
